name: 'Get release tag'
description: 'Returns release env'
author: 'Przemysław Żydek'
inputs:
  tag:
    description: 'Release tag, if exists'
    required: false
  envFromInput:
    description: 'Env provided in variable (if workflow was launched manually).'
    required: false
outputs:
  env:
    description: 'Env'
runs:
  using: 'node16'
  main: 'envProvider.js'
