name: Tests
on:
  repository_dispatch:
    types: [ test ]

jobs:
  get-affected:
    name: Get affected projects
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: ${{ github.event.client_payload.number || github.event.client_payload.ref }}
    outputs:
      affected: ${{ steps.affected.outputs.affected }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          fetch-depth: 0
          repository: ${{ secrets.REPOSITORY }}
          ref: ${{ github.event.client_payload.github.ref }}

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('package-lock.json') }}
          restore-keys: nodemodules-

      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Install action dependencies
        run: npm install --prefix .github/actions

      - name: Affected
        id: affected
        uses: ./.github/actions/list-affected
        with:
          base: 'origin/test'
          head: 'HEAD'

      - name: Output vars
        run: |
          echo "Affected: ${{ steps.affected.outputs.affected }}"
          echo "Affected JSON: ${{ fromJSON(steps.affected.outputs.affected) }}"

  units:
    name: Unit tests & linting
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: ${{ github.event.client_payload.number || github.event.client_payload.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          fetch-depth: 0
          repository: ${{ secrets.REPOSITORY }}
          ref: ${{ github.event.client_payload.github.ref }}

      - name: Create GitHub App Installation Token
        uses: jnwng/github-app-installation-token-action@v2
        id: installation_token
        with:
          appId: ${{ secrets.GH_APP_ID }}
          installationId: ${{ secrets.GH_APP_INSTALLATION_ID }}
          privateKey: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          check_id: ${{github.event.client_payload.unit_tests_check_id}}
          token: ${{ steps.installation_token.outputs.token }}
          sha: ${{github.event.client_payload.github.sha}}
          status: "in_progress"
          repo: ${{ secrets.REPOSITORY }}
          details_url: ${{ github.server_url }}/TheUnderScorer/tvgether/actions/runs/${{ github.run_id }}

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('package-lock.json') }}
          restore-keys: nodemodules-

      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Create .env file
        run: |
          echo "NX_ENABLE_DEBUG=true" >> .env
          echo "NX_WEBSITE_URL=http://localhost:3000" >> .env
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/db" >> .env

      - name: Start database
        run: docker-compose up -d db && sleep 10

      - name: Migrate database
        run: npx nx run backend-db:generate && npx nx run backend-db:migrate

      - name: Lint
        run: npx nx affected --target=lint --base=origin/test --head=HEAD --parallel=3

      - name: Test
        run: npx nx affected --target=test --base=origin/test --head=HEAD --parallel=3

      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ steps.installation_token.outputs.token }}
          sha: ${{github.event.client_payload.github.sha}}
          conclusion: ${{ job.status }}
          status: "completed"
          repo: ${{ secrets.REPOSITORY }}
          check_id: ${{github.event.client_payload.unit_tests_check_id}}
          details_url: ${{ github.server_url }}/TheUnderScorer/tvgether/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}

  e2e-browser-extension:
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [ 1, 2, 3 ]
        shardTotal: [ 3 ]
    name: Browser Extension e2e tests
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.get-affected.outputs.affected).browser-extension }}
    env:
      NX_BRANCH: ${{ github.event.client_payload.number || github.event.client_payload.ref }}
    needs:
      - get-affected
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          fetch-depth: 0
          repository: ${{ secrets.REPOSITORY }}
          ref: ${{ github.event.client_payload.github.ref }}

      - name: Create GitHub App Installation Token
        uses: jnwng/github-app-installation-token-action@v2
        id: installation_token
        with:
          appId: ${{ secrets.GH_APP_ID }}
          installationId: ${{ secrets.GH_APP_INSTALLATION_ID }}
          privateKey: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          check_id: ${{github.event.client_payload.e2e_browser_extension_check_id}}
          token: ${{ steps.installation_token.outputs.token }}
          sha: ${{github.event.client_payload.github.sha}}
          status: "in_progress"
          repo: ${{ secrets.REPOSITORY }}
          details_url: ${{ github.server_url }}/TheUnderScorer/tvgether/actions/runs/${{ github.run_id }}

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('package-lock.json') }}
          restore-keys: nodemodules-

      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Setup playwright
        run: npx playwright install-deps && npx playwright install

      - name: Create .env file
        run: |
          cp .env.dist .env
          echo "NX_GIPHY_API_KEY=${{ secrets.GIPHY_API_KEY }}" >> .env

      - name: Start database
        run: docker-compose up -d db && sleep 10

      - name: Migrate database
        run: npx nx run backend-db:generate && npx nx run backend-db:migrate

      - name: Build server
        run: npx nx run server:build:production --skip-nx-cache

      - name: Start server
        run: docker compose up -d server && sleep 10
        env:
          NX_WEBSITE_URL: http://localhost:3000

      - name: Start video playground
        run: npx nx run video-playground:serve:production & sleep 10

      - name: Build website
        run: npx nx build website --production

      - name: Start website
        working-directory: dist/apps/website
        run: npm run start & sleep 10
        env:
          NX_SERVER_URL: http://localhost:8080
          NX_CHROME_EXTENSION_STORE_URL: https://chrome.google.com/webstore/detail/tvgether/nnjgjgjgjgjgjgjgjgjgjgjg

      - name: Build extension
        run: npx nx build browser-extension --production --skip-nx-cache
        env:
          NX_WEBSITE_URL: http://localhost:3000

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npx nx run browser-extension-e2e:e2e  --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: browser-extension
          path: dist/apps/browser-extension

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: test-artifact-${{ matrix.os }}-browser-extension
          path: artifacts

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: browser-contexts
          path: apps/browser-extension-e2e/src/contexts/**/chrome_debug.log

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: trace-${{ matrix.os }}-browser-extension
          path: test-results

      - name: Print server logs
        if: ${{ always() }}
        run: docker compose logs server

      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ steps.installation_token.outputs.token }}
          sha: ${{github.event.client_payload.github.sha}}
          conclusion: ${{ job.status }}
          status: "completed"
          repo: ${{ secrets.REPOSITORY }}
          check_id: ${{github.event.client_payload.e2e_browser_extension_check_id}}
          details_url: ${{ github.server_url }}/TheUnderScorer/tvgether/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}

  e2e-server:
    name: Server e2e tests
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.get-affected.outputs.affected).server }}
    env:
      NX_BRANCH: ${{ github.event.client_payload.number || github.event.client_payload.ref }}
    needs:
      - get-affected
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          fetch-depth: 0
          repository: ${{ secrets.REPOSITORY }}
          ref: ${{ github.event.client_payload.github.ref }}

      - name: Create GitHub App Installation Token
        uses: jnwng/github-app-installation-token-action@v2
        id: installation_token
        with:
          appId: ${{ secrets.GH_APP_ID }}
          installationId: ${{ secrets.GH_APP_INSTALLATION_ID }}
          privateKey: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          check_id: ${{github.event.client_payload.e2e_server_check_id}}
          token: ${{ steps.installation_token.outputs.token }}
          sha: ${{github.event.client_payload.github.sha}}
          status: "in_progress"
          repo: ${{ secrets.REPOSITORY }}
          details_url: ${{ github.server_url }}/TheUnderScorer/tvgether/actions/runs/${{ github.run_id }}

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('package-lock.json') }}
          restore-keys: nodemodules-

      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Create .env file
        run: |
          cp .env.dist .env

      - name: Start database
        run: docker-compose up -d db && sleep 10

      - name: Migrate database
        run: npx nx run backend-db:generate && npx nx run backend-db:migrate

      - name: Build server
        run: npx nx run server:build:production

      - name: Start server
        run: docker compose up -d server && sleep 10
        env:
          NX_WEBSITE_URL: http://localhost:3000

      - name: Run tests
        run: npx nx run server-e2e:e2e --runInBand
        env:
          NX_ENABLE_DEBUG: false

      - name: Print server logs
        if: ${{ always() }}
        run: docker compose logs server

      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ steps.installation_token.outputs.token }}
          sha: ${{github.event.client_payload.github.sha}}
          conclusion: ${{ job.status }}
          status: "completed"
          repo: ${{ secrets.REPOSITORY }}
          check_id: ${{github.event.client_payload.e2e_server_check_id}}
          details_url: ${{ github.server_url }}/TheUnderScorer/tvgether/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}

